name: functions_framework
description: >-
  FaaS (Function as a service) framework for writing portable Dart functions
publish_to: none

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  shelf: ^0.7.9
