name: functions_framework
version: 0.1.0
description: >-
  FaaS (Function as a service) framework for writing portable Dart functions
repository: https://github.com/GoogleCloudPlatform/functions-framework-dart

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  args: ^1.6.0
  built_collection: ^4.3.2
  built_value: ^7.1.0
  shelf: ^0.7.9

dev_dependencies:
  build_runner: ^1.10.2
  built_value_generator: ^7.1.0
