name: functions_framework_dart
description: FaaS (Function as a service) framework for writing portable Dart functions
version: 0.0.1

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  args: ^1.6.0
  build: ^1.3.0
  built_value: ^7.1.0
  glob: ^1.2.0
  path: ^1.7.0
  reflectable: ^2.2.8
  shelf: ^0.7.9

dev_dependencies:
  build_runner: ^1.10.2
  pedantic: ^1.9.0
