# Created with package:mono_repo v3.1.0-beta.3
name: Dart CI
on:
  push:
    branches:
      - main
      - master
  pull_request:
  schedule:
    - cron: "0 0 * * 0"
defaults:
  run:
    shell: bash
env:
  PUB_ENVIRONMENT: bot.github

jobs:
  job_001:
    name: mono_repo self validate
    runs-on: ubuntu-latest
    steps:
      - uses: cedx/setup-dart@v2
        with:
          release-channel: stable
          version: latest
      - run: dart --version
      - uses: actions/checkout@v2
      - run: pub global activate mono_repo 3.1.0-beta.3
      - run: pub global run mono_repo generate --validate
  job_002:
    name: "OS: linux; SDK: dev; PKGS: examples/hello, functions_framework, functions_framework_builder; TASKS: [`dartfmt -n --set-exit-if-changed .`, `dartanalyzer --fatal-infos .`]"
    runs-on: ubuntu-latest
    steps:
      - uses: cedx/setup-dart@v2
        with:
          release-channel: dev
      - run: dart --version
      - uses: actions/checkout@v2
      - env:
          PKGS: examples/hello functions_framework functions_framework_builder
          TRAVIS_OS_NAME: linux
        run: tool/ci.sh dartfmt dartanalyzer_0
  job_003:
    name: "OS: linux; SDK: 2.10.0; PKGS: examples/hello, functions_framework, functions_framework_builder; TASKS: `dartanalyzer .`"
    runs-on: ubuntu-latest
    steps:
      - uses: cedx/setup-dart@v2
        with:
          release-channel: stable
          version: "2.10.0"
      - run: dart --version
      - uses: actions/checkout@v2
      - env:
          PKGS: examples/hello functions_framework functions_framework_builder
          TRAVIS_OS_NAME: linux
        run: tool/ci.sh dartanalyzer_1
